zuul:
  routes:
    main-service:
      sensitiveHeaders: "*"

server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cas:
  serverName: localhost:8082
  casServerUrlPrefix: http://13.jiaweiwei.net:8055/cas
  casServerLoginUrl: http://13.jiaweiwei.net:8055/cas/login
  #casServerUrlPrefix: http://localhost:8078/cas
  #casServerLoginUrl: http://localhost:8078/cas/login
  singleSignOut: true
  loginUserHandle: com.nokia.CellplanServer.sso.SsoAuthHandleImpl
  characterEncoding: UTF-8
  encoding: UTF-8
  skipUrls: /*.json